backend:
  name: git-gateway
  branch: main

site_url: https://epgt-dynamique.netlify.app
local_backend: true

media_folder: "images"
public_folder: "/images"

collections:
  - name: "articles"
    label: "Articles"
    folder: "articles"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Titre", name: "title", widget: "string" }
      - { label: "Date", name: "date", widget: "datetime" }
      - { label: "Contenu", name: "body", widget: "markdown" }
